# Generated by Django 4.2.20 on 2025-05-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Num1", models.FloatField()),
                ("town", models.CharField(max_length=100)),
                ("Num2", models.CharField(max_length=100)),
                ("Geography", models.CharField(max_length=100)),
                ("longitude", models.FloatField()),
                ("latitude", models.FloatField()),
                ("irrigation", models.CharField(max_length=100)),
                ("groundwater", models.FloatField()),
                ("drawdown", models.FloatField()),
                ("final", models.FloatField()),
                ("age", models.FloatField()),
                ("welldeep", models.FloatField()),
                ("wellr", models.FloatField()),
                ("mertial", models.CharField(max_length=100)),
                ("elevation", models.FloatField()),
                ("power", models.FloatField()),
                ("lift", models.FloatField()),
                ("flow", models.FloatField()),
                ("convert", models.FloatField()),
            ],
        ),
    ]
