# Generated by Django 4.2.20 on 2025-06-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WellData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.IntegerField()),
                ("town", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("longitude", models.FloatField()),
                ("latitude", models.FloatField()),
                ("irrigation_method", models.CharField(max_length=100)),
                ("groundwater_depth", models.FloatField()),
                ("drawdown", models.FloatField()),
                ("final_groundwater_depth", models.FloatField()),
                ("well_age", models.FloatField()),
                ("well_depth", models.FloatField()),
                ("well_diameter", models.FloatField()),
                ("well_casing_material", models.CharField(max_length=100)),
                ("wellhead_elevation", models.FloatField()),
                ("power", models.FloatField()),
                ("head", models.FloatField()),
                ("flow", models.FloatField()),
                ("conversion_factor", models.FloatField()),
            ],
        ),
    ]
