# Generated by Django 4.2.20 on 2025-06-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groundwater", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="welldata",
            name="code",
            field=models.CharField(max_length=100, verbose_name="井编码"),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="conversion_factor",
            field=models.FloatField(verbose_name="以电折水系数"),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="drawdown",
            field=models.FloatField(verbose_name="水位下降值"),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="final_groundwater_depth",
            field=models.FloatField(verbose_name="最终地下水埋深"),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="flow",
            field=models.FloatField(verbose_name="流量（m³/h）"),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="groundwater_depth",
            field=models.FloatField(verbose_name="初始地下水埋深"),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="head",
            field=models.FloatField(verbose_name="扬程（m）"),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="index",
            field=models.IntegerField(verbose_name="编号"),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="irrigation_method",
            field=models.CharField(max_length=100, verbose_name="灌溉方式"),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="latitude",
            field=models.FloatField(verbose_name="纬度"),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="location",
            field=models.CharField(max_length=200, verbose_name="位置"),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="longitude",
            field=models.FloatField(verbose_name="经度"),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="power",
            field=models.FloatField(verbose_name="功率（kW）"),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="town",
            field=models.CharField(max_length=100, verbose_name="乡镇"),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="well_age",
            field=models.IntegerField(verbose_name="井龄（年）"),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="well_casing_material",
            field=models.CharField(max_length=100, verbose_name="井管材质"),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="well_depth",
            field=models.FloatField(verbose_name="井深（m）"),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="well_diameter",
            field=models.FloatField(verbose_name="井径（mm）"),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="wellhead_elevation",
            field=models.FloatField(verbose_name="井口高程"),
        ),
    ]
