# Generated by Django 4.2.20 on 2025-06-07 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "groundwater",
            "0002_alter_welldata_code_alter_welldata_conversion_factor_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="welldata",
            options={
                "ordering": ["town", "code"],
                "verbose_name": "井数据",
                "verbose_name_plural": "井数据",
            },
        ),
        migrations.AddField(
            model_name="welldata",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="创建时间",
            ),
        ),
        migrations.AddField(
            model_name="welldata",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="code",
            field=models.CharField(max_length=20, unique=True, verbose_name="井编码"),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="drawdown",
            field=models.FloatField(verbose_name="水位下降值(m)"),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="final_groundwater_depth",
            field=models.FloatField(verbose_name="最终地下水埋深(m)"),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="flow",
            field=models.FloatField(verbose_name="流量(m³/h)"),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="groundwater_depth",
            field=models.FloatField(verbose_name="初始地下水埋深(m)"),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="head",
            field=models.FloatField(verbose_name="扬程(m)"),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="index",
            field=models.IntegerField(unique=True, verbose_name="序号"),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="irrigation_method",
            field=models.CharField(
                choices=[
                    ("喷灌", "喷灌"),
                    ("滴灌", "滴灌"),
                    ("漫灌", "漫灌"),
                    ("其他", "其他"),
                ],
                max_length=50,
                verbose_name="灌溉方式",
            ),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="latitude",
            field=models.DecimalField(
                decimal_places=6,
                help_text="格式: 度(°)",
                max_digits=8,
                verbose_name="纬度",
            ),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="longitude",
            field=models.DecimalField(
                decimal_places=6,
                help_text="格式: 度(°)",
                max_digits=9,
                verbose_name="经度",
            ),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="power",
            field=models.FloatField(verbose_name="功率(kW)"),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="town",
            field=models.CharField(max_length=50, verbose_name="乡镇"),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="well_age",
            field=models.PositiveIntegerField(verbose_name="井龄(年)"),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="well_casing_material",
            field=models.CharField(
                choices=[
                    ("钢管", "钢管"),
                    ("PVC", "PVC"),
                    ("混凝土", "混凝土"),
                    ("其他", "其他"),
                ],
                max_length=50,
                verbose_name="井管材质",
            ),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="well_depth",
            field=models.FloatField(verbose_name="井深(m)"),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="well_diameter",
            field=models.FloatField(verbose_name="井径(mm)"),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="wellhead_elevation",
            field=models.FloatField(verbose_name="井口高程(m)"),
        ),
        migrations.AddIndex(
            model_name="welldata",
            index=models.Index(fields=["town"], name="groundwater_town_5619a3_idx"),
        ),
        migrations.AddIndex(
            model_name="welldata",
            index=models.Index(fields=["code"], name="groundwater_code_da890f_idx"),
        ),
        migrations.AddIndex(
            model_name="welldata",
            index=models.Index(
                fields=["longitude", "latitude"], name="groundwater_longitu_de41c2_idx"
            ),
        ),
    ]
