# Generated by Django 4.2.20 on 2025-06-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groundwater", "0003_alter_welldata_options_welldata_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="welldata",
            name="code",
            field=models.CharField(
                db_index=True, max_length=20, unique=True, verbose_name="井编码"
            ),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="conversion_factor",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="以电折水系数"
            ),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="drawdown",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="水位下降值(m)"
            ),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="final_groundwater_depth",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="最终地下水埋深(m)"
            ),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="flow",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="流量(m³/h)"
            ),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="groundwater_depth",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="初始地下水埋深(m)"
            ),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="head",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="扬程(m)"
            ),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="index",
            field=models.IntegerField(db_index=True, unique=True, verbose_name="序号"),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="irrigation_method",
            field=models.CharField(
                choices=[
                    ("喷灌", "喷灌"),
                    ("滴灌", "滴灌"),
                    ("漫灌", "漫灌"),
                    ("其他", "其他"),
                ],
                default="喷灌",
                max_length=50,
                verbose_name="灌溉方式",
            ),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="latitude",
            field=models.CharField(
                db_index=True,
                help_text="格式: 度(°)",
                max_length=50,
                verbose_name="纬度",
            ),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="longitude",
            field=models.CharField(
                db_index=True,
                help_text="格式: 度(°)",
                max_length=50,
                verbose_name="经度",
            ),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="power",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="功率(kW)"
            ),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="town",
            field=models.CharField(db_index=True, max_length=50, verbose_name="乡镇"),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="well_age",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="井龄(年)"
            ),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="well_casing_material",
            field=models.CharField(
                choices=[
                    ("钢管", "钢管"),
                    ("PVC", "PVC"),
                    ("混凝土", "混凝土"),
                    ("其他", "其他"),
                ],
                default="钢管",
                max_length=50,
                verbose_name="井管材质",
            ),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="well_depth",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="井深(m)"
            ),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="well_diameter",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="井径(mm)"
            ),
        ),
        migrations.AlterField(
            model_name="welldata",
            name="wellhead_elevation",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="井口高程(m)"
            ),
        ),
    ]
